Gon1782/Team-Everest

.gitignore
babel.config.js
package-lock.json
package.json
src/App.tsx
src/common/api/firebase.ts
src/pages/Landing.tsx
src/shared/Router.tsx
webpack.config.js

feat. 환경변수 설정

---

src/components/header/Header.tsx
src/shared/Router.tsx
webpack.config.js

[feat] 헤더 UI 작업

---

package-lock.json
src/components/banner/Banner.tsx
src/components/header/Header.tsx
src/pages/Main/MainPage.tsx
src/shared/Router.tsx

메인페이지 - 상단 배너 UI 작업 및 배너 컴포넌트 분리

[feat] 메인페이지 배너 UI

---

src/components/calender/CalenderView.tsx
src/components/calender/Main.tsx
src/components/calender/TourList.tsx
src/recoil/atom/MyPlan.ts

[feat] 일정 페이지 수정

---

src/components/MyPlan/Main.tsx
src/components/main/bestTravelPlan/BestTravelPlan.tsx
webpack.config.js

[feat] 일정 페이지, 메인페이지 일정카드 소스 수정

[feat] 일정 페이지, 메인페이지 일정카드 소스 수정

---

src/components/MyPlan/CalenderView.tsx
src/components/MyPlan/Main.tsx
src/components/MyPlan/PlanScheduleList.tsx
src/components/MyPlan/StartEndDate.tsx
src/components/MyPlan/TourList.tsx
src/recoil/atom/MyPlan.ts

[feat] 사용자별 일정 페이지 view 수정

---

src/components/header/Header.tsx
src/components/header/SearchModal.tsx
src/components/main/bestTravelPlan/BestTravelPlan.tsx

[refactor] 헤더 검색창 커스텀훅으로 리팩토링

---

public/index.html
src/components/MyPlan/EventMap.tsx
src/components/MyPlan/Main.tsx
src/components/MyPlan/SidePage.tsx

[feat] 일정만들기 페이지용 맵 컴포넌트 생성

---

src/components/Detail/DetailInfo.tsx
src/components/MyPlan/EventMap.tsx
src/components/MyPlan/EventMemo.tsx
src/components/MyPlan/EventTime.tsx
src/components/MyPlan/Main.tsx
src/components/MyPlan/MyPlannerHandler.ts
src/components/MyPlan/ScheduleList.tsx
src/components/MyPlan/TourList.tsx
src/recoil/atom/MyPlan.ts

[feat] 지도 추가, 일정 순서기준으로 지도 선 그리기

[feat] 지도 추가, 일정 순서기준으로 지도 선 그리기

---

src/components/MyPlan/MyPlannerHandler.ts
src/components/MyPlan/TourList.tsx

[update] 일정 저장 오류 수정

---

src/components/MyPlan/Event.tsx
src/components/MyPlan/EventDropDown.tsx
src/components/MyPlan/EventMap.tsx
src/components/MyPlan/EventMemo.tsx
src/components/MyPlan/EventTime.tsx
src/components/MyPlan/Main.tsx
src/components/MyPlan/MyPlannerHandler.ts
src/components/MyPlan/ScheduleDate.tsx
src/components/MyPlan/ScheduleList.tsx
src/recoil/atom/MyPlan.ts

[update] 드롭다운에 관광지 디테일 정보 안나타나는 문제 수정

---

src/common/api/detailApi.ts
src/components/MyPlan/CalenderView.tsx
src/components/MyPlan/Event.tsx
src/components/MyPlan/EventDropDown.tsx
src/components/MyPlan/EventMap.tsx
src/components/MyPlan/EventMemo.tsx
src/components/MyPlan/EventTime.tsx
src/components/MyPlan/Main.tsx
src/components/MyPlan/ScheduleDate.tsx
src/components/MyPlan/ScheduleList.tsx
src/components/MyPlan/SelectBox.tsx
src/components/MyPlan/SidePage.tsx
src/components/MyPlan/TourList.tsx

[feat] 관광지 검색 야매 무한 스크롤링

---

src/components/MyPlan/EventDropDown.tsx
src/components/MyPlan/EventMemo.tsx
src/components/MyPlan/Main.tsx
src/recoil/atom/MyPlan.ts

[update] 메모 수정

---

src/components/Citymap/CityInfoModal.tsx
src/components/MyPage/MyPlanner/MyPlanner.tsx
src/components/MyPlan/EventDropDown.tsx
src/components/MyPlan/EventTime.tsx
src/components/MyPlan/Main.tsx
src/components/MyPlan/MyPlannerHandler.ts
src/components/main/bestTravelPlan/BestTravelPlan.tsx
src/recoil/atom/MyPlan.ts
src/shared/Router.tsx

[update] 기능 수정

---

src/components/button/ScrollToTopBtn.tsx
src/components/header/Header.tsx
src/pages/Layout/Layout.tsx

스크롤탑 버튼 클릭시 상단 이동 중 멈춤 현상 버그 개선

[fix] 스크롤탑 버튼 중간 멈춤 버그 개선

---

src/components/main/topCityBanner/TopCityBanner.tsx

메인 페이지 - 인기도시 배너 도시명 대신 슬로건으로 교체

[fix] 메인 페이지 - 인기도시 슬로건 적용

---

src/common/api/tourApi.ts
src/components/Detail/Landmark/Landmark.tsx
src/components/MyPage/MyPlanner/MyPlanner.tsx
src/components/MyPage/MyPlanner/style/MyPlannerStyled.tsx
src/components/MyPlan/EventMap.tsx
src/components/MyPlan/Main.tsx
src/components/MyPlan/MyPlannerHandler.ts
src/components/MyPlan/ScheduleDate.tsx
src/components/MyPlan/ScheduleList.tsx
src/components/MyPlan/SelectBox.tsx
src/components/MyPlan/SidePage.tsx
src/components/MyPlan/StartEndDate.tsx
src/components/MyPlan/TourList.tsx
src/components/MyPlan/style/common.ts
src/components/main/bestTravelPlan/BestTravelPlan.tsx
src/pages/Mypage/Mypage.tsx
src/recoil/atom/MyPlan.ts

[feat] 마이페이지 데이터 갱신 및 북마크 표시, 일정 만들기 페이지 검색기능 추가

[feat] 마이페이지 데이터 갱신 및 북마크 표시, 일정 만들기 페이지 검색기능 추가

---

src/components/MyPage/MyPlanner/MyPlanner.tsx

[update] css 수정

---

src/components/MyPage/MyPlanner/MyPlanner.tsx
src/pages/Mypage/Mypage.tsx

[update] 마이페이지 일정 데이터 소스 수정

---

src/components/CityInfoList/CityInfoList.tsx
src/components/CityInfoList/CityInfoListStyled.tsx
src/components/CityInfoList/CityListItem.tsx
src/pages/CityDetail/CityDetailPage.tsx

[update] 도시상세 관광지 영역 레이아웃 변경

---

src/components/CityInfoList/CityInfoList.tsx
src/components/CityInfoList/CityInfoListStyled.tsx
src/components/CityInfoList/CityListItem.tsx

[update] 도시상세 카테고리 추가 및 CSS

---

src/components/MyPlan/Event.tsx
src/components/MyPlan/EventMap.tsx
src/components/MyPlan/HandlerBtn.tsx
src/components/MyPlan/Main.tsx
src/components/MyPlan/ScheduleList.tsx
src/components/MyPlan/SidePage.tsx
src/components/main/bestTravelPlan/BestTravelPlan.tsx

[design] 일정 페이지

---

src/common/api/tourApi.ts
src/components/Amusement/Amusement.tsx
src/components/Amusement/AmusementInfoBox.tsx
src/components/CityInfoList/CityInfoList.tsx
src/components/CityInfoList/CityListItem.tsx
src/components/Detail/DetailInfo.tsx
src/components/Detail/Landmark/Landmark.tsx
src/components/Detail/Landmark/SimilarLandmark.tsx
src/components/Detail/Landmark/style/LandmarkStyled.tsx
src/components/Detail/Review/style/ReviewStyled.tsx
src/components/Michelin/Michelin.tsx
src/components/Michelin/MichelinInfoBox.tsx
src/components/MyPage/MyReview/MyReviewBox.tsx
src/components/MyPlan/SidePage.tsx
src/components/MyPlan/TourList.tsx
src/components/common/Error.tsx
src/pages/Detail/DetailPage.tsx

[Fix] api http's'
[Style] 관광지 상세 페이지 스타일 수정

[Fix] firstimage https로 변경

---

src/components/main/eventBanner/EventSlideBanner.tsx
src/components/main/themeBanner/ThemeSlideBanner.css
src/components/main/themeBanner/ThemeSlideBanner.tsx
src/styles/Theme.ts

[design] 메인 페이지 CSS 추가 스타일링

---

src/components/main/bestTravelPlan/BestTravelPlan.tsx

[design] 메인 페이지 일정카드 폰트컬러 수정, 호버 적용

[design] 메인 페이지 일정카드 폰트컬러 수정, 호버 적용

---

src/common/api/tourApi.ts
src/components/MyPage/Profile/Profile.tsx
src/components/MyPlan/Event.tsx
src/components/MyPlan/SidePage.tsx

[design] 마이페이지 displayname , 일정 페이지 아이콘 위치 변경

[design] 마이페이지 displayname , 일정 페이지 아이콘 위치 변경

---

src/components/MyPlan/EventMap.tsx

[fix] 카카오맵 수정

---

src/components/MyPlan/ScheduleList.tsx
src/components/MyPlan/SelectBox.tsx

[fix] 일정 페이지 key

---

src/components/MyPage/MyPlanner/MyPlanner.tsx
src/components/MyPage/MyPlanner/style/MyPlannerStyled.tsx
src/components/MyPlan/CityHashTag.tsx
src/components/MyPlan/HandlerBtn.tsx
src/pages/Myplanner/MyPlanner.tsx

[design] 전체 CSS 스타일링 추가 업데이트

---

src/components/MyPlan/Event.tsx
src/components/MyPlan/EventMap.tsx
src/components/MyPlan/HandlerBtn.tsx
src/pages/Myplanner/MyPlanner.tsx
src/recoil/atom/MyPlan.ts

[fit] 카카오 맵 수정

---

src/components/MyPlan/Event.tsx
src/components/MyPlan/EventMap.tsx
src/components/common/Error.tsx
src/components/main/bestTravelPlan/BestTravelPlan.tsx

[fit] 마커 이미지 , 에러 페이지 적용
